name: Conventional Commits
on:
  pull_request:

jobs:
  build:
    name: https://www.conventionalcommits.org
    runs-on: ubuntu-latest
    steps:
      - uses: Slashgear/action-check-pr-title@v4.3.0
        with:
          regexp: "(feat|fix|docs): .++" # Regex the title should match.
          helpMessage: "Example: 'feat: example of title'"
